# Определяет версию API Kubernetes, которую вы используете для создания объекта
apiVersion: v1

# Указывает, что создаваемый объект является сервисом
kind: Service

# Секция метаданных для сервиса
metadata:
  # Имя сервиса, используемое для идентификации в кластере
  name: admission-controller

# Спецификация конфигурации сервиса
spec:
  # Указывает селектор для выбора подов, которые будут обслуживаться этим сервисом
  selector:
    # Селектор меток, который должен соответствовать меткам пода
    app: python-admission

  # Список портов, которые сервис будет предоставлять
  ports:
  - # Определяет порт, который будет открыт сервисом на стороне кластера
    port: 8001
    # Порт внутри пода, к которому сервис будет направлять трафик
    targetPort: 8001
