apiVersion: v1
kind: Pod
metadata:
  name: nfs-volume-pod
spec:
  containers:
    - name: nfs-volume-pod
      image: k8s.gcr.io/test-webserver
      volumeMounts:
        - name: cache-volume
          mountPath: /cache

  volumes:
    - name: cache-volume
      nfs:
        path: "/mnt/nfs_share"
        server: "192.168.49.1" # нужно указать адрес сервере, где находится папка nfs
        readOnly: false