apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-ram-limit
spec:
  limits:
  - default:
      memory: 100Mi
      cpu: 100m
    defaultRequest:
      memory: 100Mi
      cpu: 100m
    max:
      memory: 1Gi
      cpu: "1"
    min:
      memory: 100Mi
      cpu: 100m
    type: Container