apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-slow
spec:
  # storageClassName: "local-host-path"
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi