apiVersion: storage.k8s.io/v1
kind: StorageClass # использование провайдера, который обрабатывает запросы на создание хранилища
metadata:
  name: local-host-path
provisioner: kubernetes.io/minikube-hostpath # minikube addons enable hostpath-provisioner: Exiting due to MK_ADDON_ENABLE: enable failed: run callbacks: hostpath-provisioner is not a valid addon
# parameters:
#   type: io1 # тип хранилища в io1 (производительное SSD-хранилище).
#   iopsPerGB: "1" # количество операций ввода-вывода в секунду (IOPS) на гигабайт хранилища.
#   fsType: ext4 # тип файловой системы для созданного хранилища (ext4 в данном случае).
reclaimPolicy: Retain # хранилище не будет автоматически удалено при удалении PersistentVolumeClaim.
allowVolumeExpansion: true # расширение PersistentVolume для этого StorageClass.
volumeBindingMode: Immediate # привязка PV будет выполняться немедленно при создании PVC, а не ожидать доступного PV