apiVersion: v1
kind: Pod
metadata:
  name: demo-app
spec:
  containers:
  - name: demo-app
    image: gcr.io/google-samples/node-hello:1.0
    envFrom:
    - configMapRef:
        name: demo-app-config
    env:
      - name: JWT_ISSUER_SECOND
        valueFrom:
          configMapKeyRef:
            name: demo-app-config
            key: JWT_ISSUER