---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: server:v2