---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: server
      version: v1
  template:
    metadata:
      labels:
        app: server
        version: v1
    spec:
      containers:
        - name: server
          image: server:v1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: server
      version: v2
  template:
    metadata:
      labels:
        app: server
        version: v2
    spec:
      containers:
        - name: server
          image: server:v2

---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
    version: v1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080