apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra-best-effort
  labels:
    app: cassandra-best-effort
spec:
  serviceName: cassandra-best-effort
  replicas: 2
  selector:
    matchLabels:
      app: cassandra-best-effort
  template:
    metadata:
      labels:
        app: cassandra-best-effort
    spec:
      nodeSelector:
        kubernetes.io/hostname: minikube-m02
      containers:
        - name: cassandra
          image: gcr.io/google-samples/cassandra:v13
          imagePullPolicy: Always
          env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: CASSANDRA_SEEDS
              value: "cassandra-best-effort-0.cassandra-best-effort.default.svc.cluster.local"
            - name: CASSANDRA_CLUSTER_NAME
              value: "K8Demo"
            - name: CASSANDRA_DC
              value: "DC1-K8Demo"
            - name: CASSANDRA_RACK
              value: "Rack1-K8Demo"
          volumeMounts:
            - name: cassandra-data-be
              mountPath: /cassandra_data
  volumeClaimTemplates:
    - metadata:
        name: cassandra-data-be
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra-best-effort
  name: cassandra-best-effort
spec:
  clusterIP: None
  ports:
    - port: 9042
  selector:
    app: cassandra-best-effort