apiVersion: v1
kind: Pod
metadata:
 name: security-context-demo
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
  containers:
  - name: sec-ctx-demo
    image: busybox
    command: ["sh", "-c", "sleep 1h"]
    securityContext:
      copabilities:
      add: ["NET_ADMIN", "SYS_TIME"]