apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: example-policy
spec:
  privilleged: false
  runAsUser:
    rule: MustRunAsNonRoot
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
    - 'ephemeral'
  fsGroup:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny