apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namespace: prod

# generators:
# - {pathOrUrl}
# - ...

# transformers:
# - {pathOrUrl}
# - ...

# validators:
# - {pathOrUrl}
# - ...