---
apiVersion: v1
kind: Pod
metadata:
  name: readiness
  labels:
    app: readiness
spec:
  containers:
    - name: readiness
      image: k8s.gcr.io/busybox
      args:
        - /bin/sh
        - -c
        - echo "Creating the file";
          touch /tmp/healthy; sleep 30;
          echo "Removing the file";
          rm -rf /tmp/healthy; sleep 30;
          echo "Creating the file again";
          touch /tmp/healthy ; sleep 600
      readinessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: readiness
spec:
  selector:
    app: readiness
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
