---
apiVersion: v1
kind: Pod
metadata:
  name: startup
spec:
  containers:
    - name: startup
      image: k8s.gcr.io/busybox
      args:
        - /bin/sh
        - -c
        - sleep 30;touch /tmp/healthy; sleep 600
      startupProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        failureThreshold: 30
        periodSeconds: 5
