apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    app: nginx2
spec:
  containers:
    - name: nginx
      image: nginx
    - name: nginx2
      image: nginx
      resources:
        limits:
          memory: 1Gi


